# Generated by Django 5.1.3 on 2024-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.TextField(choices=[('Draft', 'Borrador'), ('Publish', 'Publicado')], default='Draft', max_length=20),
        ),
    ]
